<a href="https://colab.research.google.com/github/mgt412/course_notebooks/blob/master/MGT412_Lecture_1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python for Finance: Lecture 1 material

### Mathematical and logical operators

* Arithmetic operators (classical)

In [0]:
a=5+15 # addition
b=5-15 # substraction
c=5*15 # multiplication
d=5/15 # division
e=2**5 # power

a,b,c,d,e # display all results

# What is odd about the result

(20, -10, 75, 0, 32)

In [0]:
d1=5.0/15 # use float types to get correct division output
d1

0.3333333333333333

* Arithmetic operators (strings)

In [0]:
"hello"+" "+"word", "hi! "*3 # arithmetic operations on strings

('hello word', 'hi! hi! hi! ')

* Assigment opperators

In [0]:
x=3 # variable assignment
x+=2 # assignment and addition
x

5

In [0]:
y=4
y*=5 # assignment and multiplication
y

20

* Comparison operators

In [0]:
# Equality
2==2

True

In [0]:
# Inequality
5!=5

False

In [0]:
# Greater/smaller
2>-5, 2>=3, 5<10, 2<5<=5

(True, False, True, True)

* Boolean operators

In [0]:
(1==2) and (3+2==5)

False

In [0]:
(1==2) or (3+2==5)

True

In [0]:
not(1==2)

True

### Control flow

In [0]:
# IF-ELSE statement
stocks=100
capital=20
loans=100
deposits=180
x=-0.3
if stocks*(1+x)+loans-deposits<0:
    print "bankrupt"
else:
    print "still alive"

bankrupt


In [0]:
# WHILE loop
a=1
n=1
while a<100:
    a*=n
    n+=1
    print a

1
2
6
24
120


In [0]:
# FOR loop
names=["Anne", "Bob","Thomas","Daisy"]
for x in names:
    print "Hello "+x+"\n"

Hello Anne

Hello Bob

Hello Thomas

Hello Daisy



### User-defined functions

In [0]:
# Sign of a function
def sign(x):
    if x>0:
        return 1
    elif x<=0:
        return -1

**Global and local variables**

In [0]:
x=5
def sum1(y): # global x
    print x+y
def sum2(x,y): # local x
    print x+y

## Exercise: What does this function do?

In [0]:
def mysteryfunction(x,tol):
    lower=0.0
    upper=x
    temp=0.5*(lower+upper)
    while (abs(x-temp*temp)>tol):
        if temp*temp>x:
            upper=temp
        else:
            lower=temp
        temp=(upper+lower)*0.5
    return temp

### Data types in Python

In [0]:
a=10
type(a), a/4

(int, 2)

In [0]:
b=0.35
type(b), b+0.1

(float, 0.44999999999999996)

In [0]:
c="string type"
type(c)

str

In [0]:
# Examples of string methods
c.capitalize(), c.replace('st','b'), c.split(" ")

('String type', 'bring type', ['string', 'type'])

* tuples

In [0]:
t=(1,2.5,"data")
t.count("data"), t.index(1)

(1, 0)

* list

In [0]:
l=[1,2.5,"data"]
l.append([4,3]) # append at the end
l

[1, 2.5, 'data', [4, 3]]

In [0]:
l.insert(1,"insert") # insert before index
l

[1, 'insert', 2.5, 'data', [4, 3]]

In [0]:
l.remove(2.5) # remove first occurence
l

[1, 'insert', 'data', [4, 3]]

In [0]:
l[1:3] # slice a list

['insert', 'data']

* set

In [0]:
s1=set(['a','b','c','d'])
s2=set(['e','b','c','f'])

In [0]:
s1.union(s2) # union

{'a', 'b', 'c', 'd', 'e', 'f'}

In [0]:
s1.intersection(s2) # intersection

{'b', 'c'}

In [0]:
s1.difference(s2) # set difference

{'a', 'd'}

In [0]:
s1.symmetric_difference(s2) # symmetric difference (union-intersection)

{'a', 'd', 'e', 'f'}

* Working with matrices: List arrays

In [0]:
v=[0.5,0.75,1.0,1.5,2.0]
m=[v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [0]:
v[0]=-2 # list arrays work by reference pointers (changes are copied across rows)
m

[[-2, 0.75, 1.0, 1.5, 2.0],
 [-2, 0.75, 1.0, 1.5, 2.0],
 [-2, 0.75, 1.0, 1.5, 2.0]]

* Numpy arrays

In [0]:
import numpy as np
v1=np.array([0.5,0.75,1.0,1.5,2.0]) # ndarray object

In [0]:
# Operations on arrays
v1.sum(), v1.std(), v1.cumsum(), v1*2, v1**2

(5.75,
 0.53851648071345037,
 array([ 0.5 ,  1.25,  2.25,  3.75,  5.75]),
 array([ 1. ,  1.5,  2. ,  3. ,  4. ]),
 array([ 0.25  ,  0.5625,  1.    ,  2.25  ,  4.    ]))

In [0]:
# Array matrices
m1=np.array([v1,v1*2])
m1

array([[ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ]])

In [0]:
# Indexing
m1[0,2]

1.0

In [0]:
# Column sum
m1.sum(axis=0)

array([ 1.5 ,  2.25,  3.  ,  4.5 ,  6.  ])

In [0]:
# Initializing a matrix (multi-dimensional)
np.zeros((2,3,5),dtype='f',order='C') # order: column-wise is F, row-wise is C

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]], dtype=float32)

In [0]:
np.ones((2,3,5),dtype='f',order='C') # order: column-wise is F, row-wise is C

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]], dtype=float32)

In [0]:
# Operation on matrices
m1.ravel()

array([ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ,  1.  ,  1.5 ,  2.  ,  3.  ,  4.  ])

In [0]:
m1.shape

(2L, 5L)

In [0]:
m1.reshape(5,-1) # -1 is "default"

array([[ 0.5 ,  0.75],
       [ 1.  ,  1.5 ],
       [ 2.  ,  1.  ],
       [ 1.5 ,  2.  ],
       [ 3.  ,  4.  ]])

In [0]:
np.vstack((m1,m1)) # stack matrices on top

array([[ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ],
       [ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ]])

In [0]:
np.hstack((m1,m1)) # stack matrices side by side

array([[ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ,  0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ,  1.  ,  1.5 ,  2.  ,  3.  ,  4.  ]])

* Vectorization

In [0]:
v20=np.array([2,3,5])
v21=np.array([0.5,0.6,0.2])

In [0]:
v20+v21

array([ 2.5,  3.6,  5.2])

In [0]:
2*v20+3 # broadcasting scalars

array([ 7,  9, 13])

### Numpy functions

In [0]:
np.dot(v20,v21) # scalar product

3.7999999999999998

In [0]:
m2=np.ones((3,3))
np.linalg.det(m2) # determinant

0.0

In [0]:
m3=np.array([[2,5],[4,0]])
v3=np.array([0,3])
np.linalg.det(m3), np.linalg.solve(m3,v3), np.linalg.eig(m3) # matrix algebra functions

(-19.999999999999996,
 array([ 0.75, -0.3 ]),
 (array([ 5.58257569, -3.58257569]), array([[ 0.81287544, -0.66717004],
         [ 0.58243756,  0.74490545]])))

In [0]:
np.sin(np.pi), np.cos(np.pi) # trigonometric

(1.2246467991473532e-16, -1.0)

In [0]:
np.exp(1), np.log(10), np.sqrt(225) # exponential, log, square roots

(2.7182818284590451, 2.3025850929940459, 15.0)

In [0]:
np.mean(v21), np.median(v21), np.std(v21), np.corrcoef(v20,v21) # statistical operators

(0.43333333333333335,
 0.5,
 0.16996731711975949,
 array([[ 1.        , -0.83862787],
        [-0.83862787,  1.        ]]))