<a href="https://colab.research.google.com/github/mgt412/course_notebooks/blob/master/MGT412_Lecture_1_Introduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Lecture 1: Introduction to Python Programming

## Why Python?
1. *Open source:* free, powerful, and a very dynamic community to develop new packages.
2. *Cross-platform*: there are versions for Windows, OS X, and Linux.
3. *Easy syntax*: Indentation replaces cumbersome code markers, such as { and }
4. *Intuitive language*: Closest to mathematical language and pseudocode.
5. *Dynamically typed*: One does not need to declare variable types statically (some do not like this!)
6. *Interactive data analytics*: immediate feedback and intuitive data processing in IPython.

## Python Installation and Environments

>### Install on your own machine (Windows, Mac,...)

1.   Anaconda: One of the two major distributions of Python, along with Canopy (Enthought).
2.  Includes all the important packages for this course (any many others).
3.  Download (free! and cross-platform) from https://www.anaconda.com/distribution/ (select Python 3.7)

>### Run Python in the cloud

1.  For most course applications this term, we will use Google Colab platform.
2.  You can run Python code and notebooks without having to install anything!
3.  For assignments, test: always download the notebook as *.ipynb. 



## Basics: Mathematical and logical operators

>> #### Assigment opperators

In [5]:
x=3 # variable assignment
x+=2 # assignment and addition
print ("The value of x is", x)

The value of x is 5


In [7]:
y=4
y*=5 # assignment and multiplication
print ("The value of y is", y)

The value of y is 20


>>  #### Arithmetic operators (classical)




In [10]:
a=5+15 # addition
b=5-15 # substraction
c=5*15 # multiplication
d=5/15 # division
e=a**d # power

a,b,c,d,e # display all results

(20, -10, 75, 0.3333333333333333, 2.7144176165949063)

>> #### Arithmetic operators (strings)

In [15]:
add_words="hello"+" "+"world"+"\n"
multiply_word="Dracarys! " * 3
print (add_words, multiply_word)

hello world
 Dracarys! Dracarys! Dracarys! 


>> #### Comparison operators

In [16]:
# Equality
2==2

True

In [17]:
# Inequality
5!=5

False

In [18]:
# Greater/smaller
2>-5, 2>=3, 5<10, 2<5<=5

(True, False, True, True)

>>  #### Boolean (logical) operators

| AND   | True | False |
|-------|----------|-------|
|  True | True     | False |
| False | False    | False |


---



|OR   | True | False |
|-------|----------|-------|
|  True | True     | True |
| False | True   | False |

In [19]:
(1==2) and (3+2==5)

False

In [20]:
(1==2) or (3+2==5)

True

In [21]:
not(1==2)

True

### Control flow

>> #### `If-else` statements

The balance sheet of a bank looks like below:


| Assets   | Liabilities
|-------|----------|
|  Stocks 100  |  Capital 20 |
| Loans 20 | Deposits 180  |

Let $x$ be the return on stocks. If $x$ is -30\%, is the bank bankrupt?

In [24]:
stocks=100
capital=20
loans=100
deposits=180
x=-0.3
if stocks*(1+x)+loans-deposits<0:
    print ("bankrupt")
else:
    print ("still alive")

bankrupt


>> #### `While` statements

What value does the following code print?

In [0]:
a=1
n=1
while a<100:
    a*=n
    n+=1
    #print (a)

>> #### `For ` statements

1. In Python, the `for` loop operates over any list of objects, including strings!
2. This is a very powerful feature (imagine computing statistics for a given list of stock names). 
3. "Classical" format: the function \texttt{range} $\left(a,b,s\right)$ returns all natural numbers between $a$ and $b-1$, step size $s$.

In [29]:
names=["Anne", "Bob","Thomas","Daisy"]
for x in names:
    print ("Hello "+x+"\n")

Hello Anne

Hello Bob

Hello Thomas

Hello Daisy



### User-defined functions

In [0]:
# Sign of a function
def sign(x):
    if x>0:
        return 1
    elif x<=0:
        return -1

>> **Global and local variables**

Variables names assigned in a function only belong to that function (local)!

In [0]:
x=5
def sum1(y): # global x
    print (x+y)
def sum2(x,y): # local x
    print (x+y)

>> ## Caveats and common errors

1.  Indentation matters! Each code block should be intended by the same amount (tabs or spaces).
2. Do not forget the  **:** at the end of an `if, elif, else, for, while,  def` statement. 
3. Do not use augmented assignment operators (+=, *=) on new variables. 

>>> ## In-class Exercise: What does this function do?

In [0]:
def mysteryfunction(x,tol):
    lower=0.0
    upper=x
    temp=0.5*(lower+upper)
    while (abs(x-temp*temp)>tol):
        if temp*temp>x:
            upper=temp
        else:
            lower=temp
        temp=(upper+lower)*0.5
    return temp

## Data types in Python

>>> ### Integers

In [38]:
a=10
type(a), a/2

(int, 5.0)

>>> ### Float (rational numbers)

In [0]:
b=0.35
type(b), b+0.1

(float, 0.44999999999999996)

>>> ### Strings (text)

In [0]:
c="string type"
type(c)

str

In [0]:
# Examples of string methods
c.capitalize(), c.replace('st','b'), c.split(" ")

('String type', 'bring type', ['string', 'type'])

>>> ### tuples (collections)
Simple collection of arbitrary objects. Limited methods. 

In [0]:
t=(1,2.5,"data")
t.count("data"), t.index(1)

(1, 0)

>>> ### lists (also collections, more operations possible)
A collection of arbitrary objects; many methods available.

In [0]:
l=[1,2.5,"data"]
l.append([4,3]) # append at the end
l

[1, 2.5, 'data', [4, 3]]

In [0]:
l.insert(1,"insert") # insert before index
l

[1, 'insert', 2.5, 'data', [4, 3]]

In [0]:
l.remove(2.5) # remove first occurence
l

[1, 'insert', 'data', [4, 3]]

In [0]:
l[1:3] # slice a list

['insert', 'data']

>>> ### Dictionaries
Dictionaries with key-value stores. Unordered and un-sortable. Maps (generally) strings into strings or numbers.

In [0]:
d={'Last':'Doe','First':'John','Age':25, 'Height':[6,1]}

In [43]:
d['Last'], d['Height'][0]

('Doe', 6)

In [46]:
d.keys(), d.values()

(dict_keys(['Last', 'First', 'Age', 'Height']),
 dict_values(['Doe', 'John', 25, [6, 1]]))

>>> ### Sets
Mathematical sets: unordered collections of objects, repeated only once.

In [0]:
s1=set(['a','b','c','d'])
s2=set(['e','b','c','f'])

In [48]:
s1.union(s2) # union

{'a', 'b', 'c', 'd', 'e', 'f'}

In [49]:
s1.intersection(s2) # intersection

{'b', 'c'}

In [50]:
s1.difference(s2) # set difference

{'a', 'd'}

In [51]:
s1.symmetric_difference(s2) # symmetric difference (union-intersection)

{'a', 'd', 'e', 'f'}

>>> ### Working with matrices: List arrays

1. Easy to select rows or single elements. 
>>>> Example: $m[1]$ is second row, $m[1][0]$ first element of the second row.
2. Not easy to select columns! (a "row" is the primary element of the list matrix)
3. Works by reference pointers -- changes in $v$ are copied everywhere in $m$. 
>>>> Example: $v[0]=-2$. Try out $m=?$

In [52]:
v=[0.5,0.75,1.0,1.5,2.0]
m=[v,v,v]
m

[[0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0],
 [0.5, 0.75, 1.0, 1.5, 2.0]]

In [53]:
v[0]=-2 # list arrays work by reference pointers (changes are copied across rows)
m

[[-2, 0.75, 1.0, 1.5, 2.0],
 [-2, 0.75, 1.0, 1.5, 2.0],
 [-2, 0.75, 1.0, 1.5, 2.0]]

>>> ### Numpy arrays

We will import our first library: `numpy` (**num**erical **py**thon)

In [0]:
import numpy as np
v1=np.array([0.5,0.75,1.0,1.5,2.0]) # ndarray object

In [55]:
# Operations on arrays
v1.sum(), v1.std(), v1.cumsum(), v1*2, v1**2

(5.75,
 0.5385164807134504,
 array([0.5 , 1.25, 2.25, 3.75, 5.75]),
 array([1. , 1.5, 2. , 3. , 4. ]),
 array([0.25  , 0.5625, 1.    , 2.25  , 4.    ]))

In [0]:
# Array matrices
m1=np.array([v1,v1*2])
m1

array([[ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ]])

In [0]:
# Indexing
m1[0,2]

1.0

In [0]:
# Column sum
m1.sum(axis=0)

array([ 1.5 ,  2.25,  3.  ,  4.5 ,  6.  ])

In [0]:
# Initializing a matrix (multi-dimensional)
np.zeros((2,3,5),dtype='f',order='C') # order: column-wise is F, row-wise is C

array([[[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]],

       [[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]]], dtype=float32)

In [0]:
np.ones((2,3,5),dtype='f',order='C') # order: column-wise is F, row-wise is C

array([[[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]],

       [[ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.],
        [ 1.,  1.,  1.,  1.,  1.]]], dtype=float32)

In [0]:
# Operation on matrices
m1.ravel()

array([ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ,  1.  ,  1.5 ,  2.  ,  3.  ,  4.  ])

In [0]:
m1.shape

(2L, 5L)

In [0]:
m1.reshape(5,-1) # -1 is "default"

array([[ 0.5 ,  0.75],
       [ 1.  ,  1.5 ],
       [ 2.  ,  1.  ],
       [ 1.5 ,  2.  ],
       [ 3.  ,  4.  ]])

In [0]:
np.vstack((m1,m1)) # stack matrices on top

array([[ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ],
       [ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ]])

In [0]:
np.hstack((m1,m1)) # stack matrices side by side

array([[ 0.5 ,  0.75,  1.  ,  1.5 ,  2.  ,  0.5 ,  0.75,  1.  ,  1.5 ,  2.  ],
       [ 1.  ,  1.5 ,  2.  ,  3.  ,  4.  ,  1.  ,  1.5 ,  2.  ,  3.  ,  4.  ]])

* Vectorization

In [0]:
v20=np.array([2,3,5])
v21=np.array([0.5,0.6,0.2])

In [0]:
v20+v21

array([ 2.5,  3.6,  5.2])

In [0]:
2*v20+3 # broadcasting scalars

array([ 7,  9, 13])

### Numpy functions

In [0]:
np.dot(v20,v21) # scalar product

3.7999999999999998

In [0]:
m2=np.ones((3,3))
np.linalg.det(m2) # determinant

0.0

In [0]:
m3=np.array([[2,5],[4,0]])
v3=np.array([0,3])
np.linalg.det(m3), np.linalg.solve(m3,v3), np.linalg.eig(m3) # matrix algebra functions

(-19.999999999999996,
 array([ 0.75, -0.3 ]),
 (array([ 5.58257569, -3.58257569]), array([[ 0.81287544, -0.66717004],
         [ 0.58243756,  0.74490545]])))

In [0]:
np.sin(np.pi), np.cos(np.pi) # trigonometric

(1.2246467991473532e-16, -1.0)

In [0]:
np.exp(1), np.log(10), np.sqrt(225) # exponential, log, square roots

(2.7182818284590451, 2.3025850929940459, 15.0)

In [0]:
np.mean(v21), np.median(v21), np.std(v21), np.corrcoef(v20,v21) # statistical operators

(0.43333333333333335,
 0.5,
 0.16996731711975949,
 array([[ 1.        , -0.83862787],
        [-0.83862787,  1.        ]]))